
import mysql.connector
import pandas as pd

mydb_woogi0_1 = mysql.connector.connect(user='rami', password = 'rami2023#', host= '127.0.0.1', port = 3306, database='woogi0_1')

mydb_HLGD = mysql.connector.connect(user='rami', password = 'rami2023#', host= '127.0.0.1', port = 3306, database='HLGD')

mycursor_HLGD = mydb_HLGD.cursor()

try:
    mycursor_HLGD.execute('''CREATE TABLE HLGD.HL3_Activities_Upon_Login
                                SELECT *, "Adventuring" as "Activity" FROM (SELECT USR.user_id, USR.user_name, USR.school_name, USR.school_id, Act.Scene_Name as "Activity_Type", Act.scene_id as "Activity_ID", Act.`date/time` as "Date/Time" FROM (select jwt_username as "user_name", path as "scene_id", if(path = 1112, "Mines", if(path = 1114, "Mines", if(path = 1116, "Mines", if(path = 1122, "Wilds", if(path = 1123, "Veggie Shop", if(path = 920, "Super City", if(path = 820, "Fishing/Falls", if(path = 824, "Recreation", if(path = 821, "Farm", if(path = 825, "Maze", if(path = 912, "Wilds", if(path = 927, "Wilds", if(path = 930, "Wilds", if(path = 819, "Campus", if(path = 1149, "Shop", if(path = 1140, "Meadow", if(path = 1185, "Meadow", if(path = 1186, "Meadow", if(path = 1191, "Meadow", if(path = 1192, "Meadow", if(path = 1193, "Mountain", if(path = 1200, "Mountain", if(path = 1201, "Mountain", if(path = 1202, "Mountain", if(path = 1213, "Cave", if(path = 1214, "Cave",  if(path = 1215, "Cave", if(path = 1216, "Cave", if(path = 1249, "Dark Cade", if(path = 1408, "FTUE", if(path = 1294, "Gritster Race",  if(path = 1235, "PiBot Task 1", if(path = 1567, "PiBot Boss Fight", if(path = 1364, "Training Room",  if(path = 1585, "Training Room", if(path = 1277, "Student Union", if(path = 1533, "Command Center", if(path = 889, "Dungeon", if(path = 1289, "Campus Raid", if(path = -1, "Sky Island", if(path = -2, "Playground", "None"))))))))))))))))))))))))))))))))))))))))) as "Scene_Name", name as "seconds", from_unixtime(c_time) as "date/time" from woogi0_1.hlportaluseractivity where event = "USER_LEAVES_ROOM") as Act LEFT JOIN (SELECT user_id, user_name, school_name, school_id FROM HLGD.HL3_Unique_User_Logins group by user_name, school_name, school_id) USR on Act.user_name = USR.user_name where Act.Scene_Name != "None" AND USR.user_name IS NOT NULL) as ADV
                                UNION
                                SELECT *, "Video" as "Activity" FROM (SELECT USR.user_id, USR.user_name, USR.school_name, USR.school_id, "Video" as "Activity_Type", Act.video_id as "Activity_ID", Act.`Date Time` as "Date/Time" FROM (SELECT user_id, video_id, time as "Unix", LEFT(FROM_UNIXTIME(time), 10) AS "Date", FROM_UNIXTIME(time) AS "Date Time" FROM woogi0_1.wcreatevideolog WHERE `event` = 0 AND `time` > UNIX_TIMESTAMP("2022-12-01 00:00:00")) as Act LEFT JOIN (SELECT user_id, user_name, school_name, school_id FROM HLGD.HL3_Unique_User_Logins group by user_name, school_name, school_id) USR on Act.user_id = USR.user_id where USR.user_name IS NOT NULL) as VID
                                UNION
                                SELECT *, "Mission" as "Activity" FROM (SELECT USR.user_id, USR.user_name, USR.school_name, USR.school_id, "Mission" as "Activity_Type", Act.scene_id as "Activity_ID", Act.`Date Time` as "Date/Time" FROM (select user_id, LEFT(from_unixtime(c_time), 10) AS "Date", scene_id, c_time, from_unixtime(c_time) AS "Date Time" From woogi0_1.`hlmissionactivity` WHERE activity = "GAME_START") as Act LEFT JOIN (SELECT user_id, user_name, school_name, school_id FROM HLGD.HL3_Unique_User_Logins group by user_name, school_name, school_id) USR on Act.user_id = USR.user_id where USR.user_name IS NOT NULL) as MIS;''')

except:
    mycursor_HLGD.execute('DROP Table HLGD.HL3_Activities_Upon_Login;')
    mycursor_HLGD.execute('''CREATE TABLE HLGD.HL3_Activities_Upon_Login
                                SELECT *, "Adventuring" as "Activity" FROM (SELECT USR.user_id, USR.user_name, USR.school_name, USR.school_id, Act.Scene_Name as "Activity_Type", Act.scene_id as "Activity_ID", Act.`date/time` as "Date/Time" FROM (select jwt_username as "user_name", path as "scene_id", if(path = 1112, "Mines", if(path = 1114, "Mines", if(path = 1116, "Mines", if(path = 1122, "Wilds", if(path = 1123, "Veggie Shop", if(path = 920, "Super City", if(path = 820, "Fishing/Falls", if(path = 824, "Recreation", if(path = 821, "Farm", if(path = 825, "Maze", if(path = 912, "Wilds", if(path = 927, "Wilds", if(path = 930, "Wilds", if(path = 819, "Campus", if(path = 1149, "Shop", if(path = 1140, "Meadow", if(path = 1185, "Meadow", if(path = 1186, "Meadow", if(path = 1191, "Meadow", if(path = 1192, "Meadow", if(path = 1193, "Mountain", if(path = 1200, "Mountain", if(path = 1201, "Mountain", if(path = 1202, "Mountain", if(path = 1213, "Cave", if(path = 1214, "Cave",  if(path = 1215, "Cave", if(path = 1216, "Cave", if(path = 1249, "Dark Cade", if(path = 1408, "FTUE", if(path = 1294, "Gritster Race",  if(path = 1235, "PiBot Task 1", if(path = 1567, "PiBot Boss Fight", if(path = 1364, "Training Room",  if(path = 1585, "Training Room", if(path = 1277, "Student Union", if(path = 1533, "Command Center", if(path = 889, "Dungeon", if(path = 1289, "Campus Raid", if(path = -1, "Sky Island", if(path = -2, "Playground", "None"))))))))))))))))))))))))))))))))))))))))) as "Scene_Name", name as "seconds", from_unixtime(c_time) as "date/time" from woogi0_1.hlportaluseractivity where event = "USER_LEAVES_ROOM") as Act LEFT JOIN (SELECT user_id, user_name, school_name, school_id FROM HLGD.HL3_Unique_User_Logins group by user_name, school_name, school_id) USR on Act.user_name = USR.user_name where Act.Scene_Name != "None" AND USR.user_name IS NOT NULL) as ADV
                                UNION
                                SELECT *, "Video" as "Activity" FROM (SELECT USR.user_id, USR.user_name, USR.school_name, USR.school_id, "Video" as "Activity_Type", Act.video_id as "Activity_ID", Act.`Date Time` as "Date/Time" FROM (SELECT user_id, video_id, time as "Unix", LEFT(FROM_UNIXTIME(time), 10) AS "Date", FROM_UNIXTIME(time) AS "Date Time" FROM woogi0_1.wcreatevideolog WHERE `event` = 0 AND `time` > UNIX_TIMESTAMP("2022-12-01 00:00:00")) as Act LEFT JOIN (SELECT user_id, user_name, school_name, school_id FROM HLGD.HL3_Unique_User_Logins group by user_name, school_name, school_id) USR on Act.user_id = USR.user_id where USR.user_name IS NOT NULL) as VID
                                UNION
                                SELECT *, "Mission" as "Activity" FROM (SELECT USR.user_id, USR.user_name, USR.school_name, USR.school_id, "Mission" as "Activity_Type", Act.scene_id as "Activity_ID", Act.`Date Time` as "Date/Time" FROM (select user_id, LEFT(from_unixtime(c_time), 10) AS "Date", scene_id, c_time, from_unixtime(c_time) AS "Date Time" From woogi0_1.`hlmissionactivity` WHERE activity = "GAME_START") as Act LEFT JOIN (SELECT user_id, user_name, school_name, school_id FROM HLGD.HL3_Unique_User_Logins group by user_name, school_name, school_id) USR on Act.user_id = USR.user_id where USR.user_name IS NOT NULL) as MIS;''')


mydb_HLGD.close()
 